name: Docker image

on: push
# on:
#   push:
#     branches:
#       - main

jobs:
  build:
    name: "Build-and-publish"
    runs-on: ubuntu-latest
    env:
      PGHOST: localhost
      PGUSER: postgres
      PGPORT: 5432
    services:
      postgres:
        image: postgres
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure docker container
        run: |
          ls -la .
          mv .env.sample .env
          echo "DATABASE_URL=postgresql://postgres@127.0.0.1/postgres" >> .env
          cat .env
        working-directory: ./deploy/docker
      - name: Start docker container
        run: docker compose up
        working-directory: ./deploy/docker
      - name: Test app
        env:
          PORT: 7654
        run: npx zx ./scripts/test-docker-image.mjs

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create .env file
        run: |
          echo "BASE_URL=localhost:7654\nNEXTAUTH_URL=http://localhost:7654\nDATABASE_URL=\n" > .env
          cat .env
      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          # tags: basetool/basetool:latest
          tags: basetool/basetool:test_deploy
          cache-from: type=registry,ref=basetool/basetool:latest
          cache-to: type=inline
      - name: Configure docker container
        run: |
          mv .env.example .env
          echo echo "DATABASE_URL=postgresql://postgres@127.0.0.1/postgres" >> .env
        working-directory: ./deploy/docker
      - name: Start docker container
        run: docker compose up -d
        working-directory: ./deploy/docker
      - name: Test app
        run: npx zx ./scripts/test-docker-image.mjs
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          # tags: basetool/basetool:latest
          tags: basetool/basetool:test_deploy
          # cache-from: type=registry,ref=basetool/basetool:latest
          # cache-to: type=inline
