name: VPC Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASETOOL_IO_DEPLOY_REPO_FAKE: ${{secrets.BASETOOL_IO_DEPLOY_REPO_FAKE}}
      BASETOOL_IO_DEPLOY_REPO: ${{secrets.BASETOOL_IO_DEPLOY_REPO}}
    steps:
      - run: echo "https://api.github.com/repos/${{env.BASETOOL_IO_DEPLOY_REPO_FAKE}}/dispatches"
      - name: Trigger deploy
        run: |
          curl -XPOST -u "${{ secrets.BASETOOL_IO_DEPLOY_USERNAME}}:${{secrets.BASETOOL_IO_DEPLOY_SECRET}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/${{env.BASETOOL_IO_DEPLOY_REPO}}/dispatches --data '{"event_type": "deploy_application"}'
